"""add simulation_id

Revision ID: 0494b8ab864a
Revises: 81bbbd0e2e47
Create Date: 2026-08-14 11:53:40.290802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0494b8ab864a'
down_revision = '81bbbd0e2e47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('simulation_id', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_vehicles_simulation_id'), ['simulation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicles_simulation_id'))
        batch_op.drop_column('simulation_id')

    # ### end Alembic commands ###
