"""Add edge_progress to Vehicle Sprint 4.3

Revision ID: 81bbbd0e2e47
Revises: a6c58e1b54f0
Create Date: 2026-08-09 23:47:55.626219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81bbbd0e2e47'
down_revision = 'a6c58e1b54f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edge_progress', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_column('edge_progress')

    # ### end Alembic commands ###
