"""Add Vehicle model Sprint 4.1

Revision ID: a6c58e1b54f0
Revises: b7efbeaa5162
Create Date: 2026-08-09 23:40:38.472567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6c58e1b54f0'
down_revision = 'b7efbeaa5162'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('vehicle_id', sa.String(length=64), nullable=False),
    sa.Column('latitude', sa.Float(precision=8), nullable=False),
    sa.Column('longitude', sa.Float(precision=8), nullable=False),
    sa.Column('speed', sa.Float(), nullable=False),
    sa.Column('heading', sa.Float(), nullable=False),
    sa.Column('current_node', sa.String(length=64), nullable=True),
    sa.Column('current_edge', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('vehicle_id'),
    sa.UniqueConstraint('vehicle_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicles')
    # ### end Alembic commands ###
